services:
  database:
    ports:
      - "54321:5432"
    networks:
      - test_net_share
    image: postgres:15.5
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dev_test_db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  php:
    user: www-data
    networks:
      - test_net_share
    build:
      context: ./docker/php
      args:
        # Отредактируйте эти параметры, если ваш локальный пользователь имеет другие UID и GID.
        ARG_UID: 1000
        ARG_GID: 1000
    ports:
      - "9000:9000"
      - "3000:3000"
    volumes:
      - .:/var/www/symfony_docker
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/php.ini-development:/usr/local/etc/php/php.ini
    depends_on:
      - database

  nginx:
    networks:
      - test_net_share
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/symfony_docker
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

volumes:
  db-data:

networks:
  test_net_share:
    driver: bridge
